# Generated by Django 4.2.2 on 2023-06-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='type')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('total', models.IntegerField(default=10000, verbose_name='total')),
            ],
            options={
                'db_table': 'objective',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='type')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
                ('proportion', models.IntegerField(verbose_name='proportion')),
                ('total', models.IntegerField(default=10000, verbose_name='total')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crackers.objective', verbose_name='objective')),
                ('supertask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='crackers.task', verbose_name='supertask')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
