# Generated by Django 4.2.2 on 2023-06-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='objective',
            table='objectives',
        ),
        migrations.AlterModelTable(
            name='subtask',
            table='subtasks',
        ),
    ]
