# Generated by Django 4.2.2 on 2023-06-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0002_alter_objective_table_alter_subtask_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Objective',
            new_name='Task',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.DeleteModel(
            name='Subtask',
        ),
    ]
