# Generated by Django 4.2.2 on 2023-06-28 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0002_task_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='proportion',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)], verbose_name='proportion'),
        ),
    ]
