# Generated by Django 4.2.2 on 2023-06-28 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0003_alter_task_proportion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='achievement',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)], verbose_name='achievement'),
        ),
        migrations.AlterField(
            model_name='task',
            name='proportion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='proportion'),
        ),
    ]
