# Generated by Django 4.2.2 on 2023-06-23 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0003_rename_objective_task_alter_task_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='supertask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crackers.task', verbose_name='supertask'),
        ),
    ]
