# Generated by Django 4.2.2 on 2023-06-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0004_alter_task_achievement_alter_task_proportion'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='achievement',
            field=models.FloatField(default=0.0, verbose_name='achievement'),
        ),
    ]
