# Generated by Django 4.2.2 on 2023-06-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0005_objective_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='task',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='task',
            name='total',
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
    ]
