# Generated by Django 4.2.2 on 2023-06-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0006_task_completed_task_created_at_task_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='amount',
            field=models.IntegerField(default=100, verbose_name='amount'),
            preserve_default=False,
        ),
    ]
