# Generated by Django 4.2.2 on 2023-06-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0006_remove_task_duration_remove_task_objective_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
    ]
