# Generated by Django 4.2.2 on 2023-07-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0007_remove_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='marked_complete',
            field=models.BooleanField(default=False, verbose_name='marked complete'),
        ),
    ]
