# Generated by Django 4.2.2 on 2023-07-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0009_remove_task_marked_complete_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accumulative',
            field=models.BooleanField(default=False, verbose_name='accumulative'),
        ),
    ]
