# Generated by Django 4.2.2 on 2023-07-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackers', '0010_task_accumulative'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.IntegerField(default=0),
        ),
    ]
